const actionTypes = {

    // Client Actions
    SET_SETUP_STATE: 'SET_SETUP_STATE',
    SET_SETUP_STEP: 'SET_SETUP_STEP',
    SET_INPUT: 'SET_INPUT',
    SET_DEPLOY_OPEN: 'SET_DEPLOY_OPEN',
    SET_SETUP_DEFAULT_VALUES: 'SET_SETUP_DEFAULT_VALUES',
    POP_MESSAGE: 'POP_MESSAGE',
    SET_STEP_CONDITION: 'SET_STEP_CONDITION',
    SHOW_INFO_DIALOG: 'SHOW_INFO_DIALOG',
    HIDE_INFO_DIALOG: 'HIDE_INFO_DIALOG',
    
    // Server HTTP Actions
    REMOVE_SOCIAL_FROM_CLUSTER: "REMOVE_SOCIAL_FROM_CLUSTER",
    ECHO_PROJECT_DIR: "ECHO_PROJECT_DIR",
    START_STEP : "START_STEP",
    CHECK_STEP : "CHECK_STEP",
}

export default actionTypes